<?php
@header("Content-type: text/html; charset=utf-8");
$styles=array(
	array('name'=>'星光风格','image'=>'../img/xinguang.jpg','link'=>'index.php?style=xinguang'),
	array('name'=>'宇宙弹幕','image'=>'../img/danmu.png','link'=>'index.php?style=danmu'),
	array('name'=>'新年风格','image'=>'../img/xinnian.jpg','link'=>'index.php?style=xinnian'),
	array('name'=>'星空风格','image'=>'../img/xinkong.jpg','link'=>'index.php?style=xinkong'),
	array('name'=>'K歌之王','image'=>'../img/kgzw.jpg','link'=>'index.php?style=kgzw'),
	array('name'=>'商务风格','image'=>'../img/shangwu.jpg','link'=>'index.php?style=shangwu'),
	array('name'=>'酒吧风格','image'=>'../img/jiuba.jpg','link'=>'index.php?style=jiuba'),
	array('name'=>'商务风格【二】','image'=>'../img/shangwu2.jpg','link'=>'index.php?style=shangwu2'),
	array('name'=>'紫色星空','image'=>'../img/purple.jpg','link'=>'index.php?style=purple'),
	array('name'=>'青春时光','image'=>'../img/qingchun.jpg','link'=>'index.php?style=qingchun'),
	array('name'=>'广告视频','image'=>'../img/gg.jpg','link'=>'index.php?style=gg'),
	array('name'=>'星月夜','image'=>'../img/xinyueye.jpg','link'=>'index.php?style=xinyueye'),
	array('name'=>'春意盎然','image'=>'../img/spring.jpg','link'=>'index.php?style=spring'),
	array('name'=>'2016年会','image'=>'../img/2016year.jpg','link'=>'index.php?style=2016year'),
	array('name'=>'婚礼','image'=>'../img/hunli.jpg','link'=>'index.php?style=hunli'),
	array('name'=>'自定义','image'=>'../img/custome.jpg','link'=>'index.php?style=custom'),
	);
